name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Pack
      run: dotnet pack -c Release --output nuget/
    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        path: nuget/*.nupkg

      
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Test
      run: dotnet test --configuration Release
  
  publish:
    runs-on: ubuntu-latest
    needs: [pack, tests]
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: nuget
        path: nuget/
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Publish package
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json
        }
